#pragma once

#include <stdint.h>

#define L1X(x)	(0x1000 + x)

enum diag_log_code_1x {
	LOG_UIM_DATA_C						= 0x98,
	LOG_DATA_PROTOCOL_LOGGING_C				= 0x1eb,
	LOG_DATA_PROTOCOL_LOGGING_NETWORK_IP_RM_TX_80_BYTES_C	= 0x572,
	LOG_DATA_PROTOCOL_LOGGING_NETWORK_IP_RM_RX_80_BYTES_C	= 0x573,
	LOG_DATA_PROTOCOL_LOGGING_NETWORK_IP_RM_TX_FULL_C	= 0x574,
	LOG_DATA_PROTOCOL_LOGGING_NETWORK_IP_RM_RX_FULL_C	= 0x575,
	LOG_DATA_PROTOCOL_LOGGING_NETWORK_IP_UM_TX_80_BYTES_C	= 0x576,
	LOG_DATA_PROTOCOL_LOGGING_NETWORK_IP_UM_RX_80_BYTES_C	= 0x577,
	LOG_DATA_PROTOCOL_LOGGING_NETWORK_IP_UM_TX_FULL_C	= 0x578,
	LOG_DATA_PROTOCOL_LOGGING_NETWORK_IP_UM_RX_FULL_C	= 0x579,
	LOG_DATA_PROTOCOL_LOGGING_LINK_RM_TX_80_BYTES_C		= 0x57a,
	LOG_DATA_PROTOCOL_LOGGING_LINK_RM_RX_80_BYTES_C		= 0x57b,
	LOG_DATA_PROTOCOL_LOGGING_LINK_RM_TX_FULL_C		= 0x57c,
	LOG_DATA_PROTOCOL_LOGGING_LINK_RM_RX_FULL_C		= 0x57d,
	LOG_DATA_PROTOCOL_LOGGING_LINK_UM_TX_80_BYTES_C		= 0x57e,
	LOG_DATA_PROTOCOL_LOGGING_LINK_UM_RX_80_BYTES_C		= 0x57f,
	LOG_DATA_PROTOCOL_LOGGING_LINK_UM_TX_FULL_C		= 0x580,
	LOG_DATA_PROTOCOL_LOGGING_LINK_UM_RX_FULL_C		= 0x581,
	LOG_DATA_PROTOCOL_LOGGING_FLOW_RM_TX_80_BYTES_C		= 0x582,
	LOG_DATA_PROTOCOL_LOGGING_FLOW_RM_TX_FULL_C		= 0x583,
	LOG_DATA_PROTOCOL_LOGGING_FLOW_UM_TX_80_BYTES_C		= 0x584,
	LOG_DATA_PROTOCOL_LOGGING_FLOW_UM_TX_FULL_C		= 0x585,
};
