#pragma once

#include <stdint.h>

#define UMTS(x)	(0x7000 + x)

enum diag_log_code_umts {
	LOG_UMTS_NAS_GMM_STATE_LOG_PACKET_C		= 0x130,
	LOG_UMTS_NAS_MM_STATE_LOG_PACKET_C		= 0x131,
	LOG_UMTS_NAS_REG_LOG_PACKET_C			= 0x132,
	LOG_UMTS_CS_CALL_SETUP_INFO_LOG_PACKET_C	= 0x133,
	LOG_UMTS_PS_CALL_INFO_LOG_PACKET_C		= 0x134,
	LOG_UMTS_MM_INFO_LOG_PACKET_C			= 0x135,
	LOG_UMTS_NAS_PS_CONNECTION_QOS_LOG_PACKET_C	= 0x136,
	LOG_UMTS_NAS_CS_CONNECTION_BC_LOG_PACKET_C	= 0x137,
	LOG_UMTS_NAS_UE_DYNAMIC_ID_LOG_PACKET_C		= 0x138,
	LOG_UMTS_NAS_UE_STATIC_ID_LOG_PACKET_C		= 0x139,
	LOG_UMTS_NAS_OTA_MESSAGE_LOG_PACKET_C		= 0x13a,
	LOG_UMTS_NAS_CFA_MESSAGE_LOG_PACKET_C		= 0xa3b,
	LOG_UMTS_NAS_ERROR_MESSAGE_LOG_PACKET_C		= 0x13c,
	LOG_UMTS_CS_CALL_RELEASE_INFO_LOG_PACKET_C	= 0x13d,
	LOG_UMTS_CS_CALL_CHANGE_INFO_LOG_PACKET_C	= 0x13e,
};

struct diag_umts_nas_ota_msg {
	uint8_t		direction;
	uint32_t	msg_length;
	uint8_t		data[0];
} __attribute__((packed));
